[lsoa_code]
old_name = "LSOA code"
Deduced_Data_Type = "str"

[lsoa_name]
old_name = "LSOA name"
Deduced_Data_Type = "str"

[lad_code]
old_name = "LAD code"
Deduced_Data_Type = "str"

[lad_name]
old_name = "LAD name"
Deduced_Data_Type = "str"

[adjust]
old_name = "Adjust"
Deduced_Data_Type = "boolean"

[year]
old_name = "Year"
Deduced_Data_Type = "int"
